# Generated by Django 4.1.3 on 2022-12-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='image',
            field=models.ImageField(null=True, upload_to='favoritesGoods'),
        ),
    ]
