# Generated by Django 4.1.3 on 2022-12-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_alter_favorite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='description',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='title',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='price',
            field=models.IntegerField(),
        ),
    ]
